- cpu: 55
  disk: 50
  host: 8.8.8.8
  memory: 99
  name: web-01
  region: east
  status: running
  url: https://github.com
- cpu: 65
  disk: 99
  host: 8.8.8.8
  memory: 10
  name: web-02
  region: north
  status: running
  url: https://amazon.com
- cpu: 75
  disk: 12
  host: 8.8.8.8
  memory: 20
  name: web-03
  region: south
  status: stopped
  url: https://facebook.com
- cpu: 85
  disk: 45
  host: 8.8.8.8
  memory: 30
  name: web-04
  region: west
  status: running
  url: https://twitter.com
- cpu: 95
  disk: 90
  host: 8.8.8.8
  memory: 40
  name: web-05
  region: east
  status: running
  url: https://example123.com
